repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1300']
        exclude: tests/optimization/fixtures/
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
        exclude: meta.yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.3.0]
        types: [rst]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [python]
        exclude: estimagic/parameters/kernel_transformations.py
        additional_dependencies: [
            flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
            flake8-docstrings, flake8-eradicate, flake8-print, flake8-rst-docstrings,
            flake8-todo, pep8-naming, pydocstyle,
        ]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.11.1
    hooks:
        -   id: doc8
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==22.3.0]
    -   id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
        exclude: 'inference|differentiation|miscellaneous'
    -   id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/PyCQA/doc8
    rev: 0.11.1
    hooks:
    -   id: doc8
