codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 90%

ignore:
  - ".tox/**/*"
  - "release.py"
  - "setup.py"
  - "estimagic/tests/**/*"
  - "src/estimagic/optimization/subsolvers/bntr_fast.py"
  - "src/estimagic/optimization/subsolvers/_trsbox_quadratic_fast.py"
  - "src/estimagic/optimization/subsolvers/_conjugate_gradient_quadratic_fast.py"
  - "src/estimagic/optimization/subsolvers/_steihaug_toint_quadratic_fast.py"
  - "src/estimagic/optimization/subsolvers/gqtpar_fast.py"
