name: estimagic

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:
  - python=3.9
  - pip
  - setuptools_scm
  - toml
  - anaconda-client
  - bokeh>=1.3
  - ansi2html
  - click
  - conda-build
  - conda-verify
  - cyipopt
  - fuzzywuzzy
  - joblib
  - cloudpickle
  - jupyterlab
  - nbsphinx
  - numpy
  - pandas
  - pdbpp
  - pygmo
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy>=1.2.1
  - seaborn
  - plotly
  - sphinx
  - pydata-sphinx-theme>=0.3.0
  - sphinxcontrib-bibtex
  - sqlalchemy>=1.3
  - tox-conda
  - statsmodels
  - dill
  - pytask>=0.0.11
  - nlopt
  - sphinx-panels
  - pygmo
  - nb_black
  - pybaum

  - pip:
      - black
      - blackcellmagic
      - bump2version
      - pre-commit
      - Py-BOBYQA
      - DFO-LS
      - fides==0.7.4
      - gif
      - gif[matplotlib]
      - kaleido
