---
name: tranquilo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10  # dev
  - jupyterlab  # dev, docs
  - nb_black  # dev, docs
  - pdbpp  # dev
  - pip  # dev, tests, docs
  - pytest  # dev, tests
  - pytest-cov  # tests
  - pytest-xdist  # dev, tests
  - setuptools_scm  # dev
  - toml  # dev
  - estimagic  # run, tests
  - numba  # run, tests
  - numpy>=1.17.0  # run, tests
  - pandas  # run, tests
  - plotly  # run, tests
  - scipy>=1.2.1  # run, tests
  - pydata-sphinx-theme>=0.3.0  # docs
  - myst-nb  # docs
  - sphinx  # docs
  - sphinx-copybutton  # docs
  - sphinx-panels  # docs
  - sphinxcontrib-bibtex  # docs
  - pip:  # dev, tests, docs
      - black  # dev
      - blackcellmagic  # dev
      - kaleido  # dev, tests
      - pre-commit  # dev
      - -e .  # dev
