---
name: estimagic-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9
  - pip
  - setuptools_scm
  - toml

  - black
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - sphinx-panels
  - ipython
  - ipython_genutils
  - myst-nb
  - pydata-sphinx-theme>=0.3.0
  - numba
  - pybaum
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - patsy
  - joblib
  - plotly
  - ipython

  - pip:
      - ../
      - kaleido
      - Py-BOBYQA
      - DFO-LS
