---
name: tranquilo-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - setuptools_scm
  - toml
  - pip
  - estimagic
  - ipython
  - ipython_genutils
  - joblib
  - matplotlib
  - myst-nb
  - numpy
  - pandas
  - plotly
  - scipy
  - seaborn
  - sphinx
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme<=0.12.0
  - pip:
      - ../
